name: Bug report
description: Report a reproducible bug or regression.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail for maintainers to reproduce quickly.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Upload ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Paste relevant logs or stack traces. Redact tokens/keys.
      render: shell
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Python version:
        - Command run:
        - Mode (dry/live):
    validations:
      required: true
