name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: What user problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the desired behavior and API/UX.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any workarounds or other approaches?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Mockups, examples, or references.
